apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-server-ingress-cert
  namespace: projects
spec:
  secretName: home-server-ingress-cert-secret
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  ipAddresses:
    - 192.168.10.161
  issuerRef:
    name: letsencrypt-route53
    kind: ClusterIssuer
