apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-route53
spec:
  acme:
    solvers:
      - selector:
          dnsZones:
            - 'mlem-mlem.net'
        dns01:
          route53:
            region: eu-central-1
            accessKeyIDSecretRef:
              name: aws-access-key-id
              key: access-key-id
            secretAccessKeySecretRef:
              name: aws-secret-access-key
              key: secret-access-key
