apiVersion: v1
kind: Secret
metadata:
  name: aws-access-key-id
  namespace: cert-manager
data:
  AWS_ACCESS_KEY_ID: {{ b64enc .Values.accessKeyId }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret-access-key
  namespace: cert-manager
data:
  AWS_SECRET_ACCESS_KEY: {{ b64enc .Values.secretAccessKey }}
type: Opaque
