apiVersion: v1
kind: Secret
metadata:
  name: aws-cred-route53
  namespace: kube-system
data:
  AWS_ACCESS_KEY_ID: {{ b64enc .Values.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ b64enc .Values.secretAccessKey }}
  AWS_REGION: {{ b64enc .Values.awsRegion }}
  AWS_HOSTED_ZONE_ID: {{ b64enc .Values.hostedZoneId }}
type: Opaque